// Generated by CoffeeScript 1.6.3
(function() {
  exports.index = function(req, res) {
    var user;
    user = req.session.passport.user;
    if (user) {
      console.log(user);
    }
    console.log(req.session, 'in routes');
    res.render("index", {
      title: "Express",
      user: user
    });
  };

  exports.test = function(req, res) {
    var user;
    user = req.session.passport.user;
    return res.render("test", {
      user: user
    });
  };

  exports.login = function(req, res) {
    return res.render("login");
  };

}).call(this);
