// Generated by CoffeeScript 1.6.3
(function() {
  exports.runQuery = function(client, q, args, cb) {
    var _this = this;
    client.on('drain', client.end.bind(client));
    client.connect();
    return client.query(q, args, function(err, result) {
      if (err) {
        console.log('couldnt run query', err);
        return;
      }
      return cb(result.rows);
    });
  };

}).call(this);
