// Generated by CoffeeScript 1.6.3
(function() {
  var WSC;

  WSC = (function() {
    function WSC(ws) {
      this.ws = ws;
    }

    WSC.prototype.onmessage = function(msg) {
      var data,
        _this = this;
      data = msg.data || {};
      return this[msg.request](data, function(r) {
        var res;
        res = JSON.stringify({
          response: msg.request,
          data: r
        });
        return _this.ws.send(res);
      });
    };

    return WSC;

  })();

  exports.WSC = WSC;

}).call(this);
