// Generated by CoffeeScript 1.6.3
(function() {
  var WsHandler;

  WsHandler = (function() {
    function WsHandler() {}

    WsHandler.prototype.convos = [];

    WsHandler.prototype.addConversations = function(cons) {
      return this.convos = this.convos.concat(cons);
    };

    WsHandler.prototype.onmessage = function(msg) {
      var con, convo, _i, _len, _ref;
      _ref = this.convos;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        con = _ref[_i];
        if (con[msg.request]) {
          convo = con;
        }
      }
      if (convo) {
        return convo.onmessage(msg);
      } else {
        return console.log("no response for " + msg.request + " request");
      }
    };

    return WsHandler;

  })();

  exports.WsHandler = WsHandler;

}).call(this);
